name: Go GHactions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      # Run testing on the code
      - name: Run testing
        run: cd test && go test -v ./...
